import './globals.css';
import { Roboto } from 'next/font/google';

import Side from '@/components/Side';
import Divider from '@/components/Divider';
import Tabs from '@/components/TabsSection';
import Greeting from '@/components/Greeting';
import { ScrollToTop } from '@/components/ScrollToTop';

const font = Roboto({ weight: ['300', '400', '500'], display: 'swap', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`dark ${font.className}`}>
      <body>
        <div className='container mx-auto px-1 min-h-screen flex flex-col md:flex-row w-full'>
          <aside className='mt-2 md:mt-12 md:basis-1/4'>
            <Side />
          </aside>
          <Divider />
          <main className='md:mt-12 flex-1'>
            <div className='mx-6 mockup-code h-max'>
              <Greeting />
              <Tabs>{children}</Tabs>
              <ScrollToTop />
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
